quarkus.datasource.db-kind=mysql
quarkus.datasource.username=pw2
quarkus.datasource.password=pw2
quarkus.datasource.devservices.port=3306

quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.swagger-ui.always-include=true
mp.openapi.extensions.smallrye.info.title=Livros (hexagonal)
mp.openapi.extensions.smallrye.info.version=1.0.0
