remote_theme: pmarsceill/just-the-docs

favicon_ico: "/imgs/fav.png"

aux_links:
  "Github":
    - "https://github.com/rodrigoprestesmachado/vvs"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2026 <a href='https://rpmhub.dev'>RPM Hub</a>. Distributed by CC-BY-4.0 license."
